### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by brh55** [brh55/botkit-discord#19]
I'm busy with new things in my life, and would love to assign a few maintainers to the project. Please let me know if you are interested.

**Comment by YannZeRookie** [comment]
Unfortunately, I cannot offer my help because I'm a beginner with NodeJS, BotKit, etc. For example, I was not able to understand how your project interacted with Botkit and Discord.js, and so could not offer a Pull Request for Botkit 4.

Maybe a solution would be for you to contact the Botkit people and offer them to take over your code ? This would give them a quick path to add another official Platform Adapter to their list of supported platforms at https://botkit.ai/docs/v4/platforms/ ? They don't support Discord in there yet, which I think is a big hole on their list.

Thanks!

**Comment by brh55** [comment]
That's a good point, I'm actually connected with the creator of Botkit. I'll need to perform a rewrite for that to be a universal adapter. Hoping someone can fill that gap!

**Comment by joemcmahon** [comment]
I'm actively using botkit-discord right now, so I'll be happy to support it interim while/if you're doing the rewrite.

**Comment by brh55** [comment]
Excellent, I'll invite you as a collaborator @joemcmahon if you are interested. I was interest in doing a rewrite, but I haven't had a need for building a discord bot lately, fresh out of ideas lately :(.

**Comment by brh55** [comment]
I've added @joemcmahon. If anyone else is interested, feel free to submit a new issue.
